### PR TITLE
Update Adafruit_FeatherOLED.h

### PR DESCRIPTION
**Pull request by axelmagnus**
Issue #29

- Fixes error in voltage divider formula for ESP8266

- no limitations that i can fathom

my first PR! did i do it right?

### CODE REVIEW

**Comment by caternuson** [comment]
Hey. Thanks. You got the ball rolling at least. So it's a start!

Now you're dealing with the CI (continuous integration) checks. This is just a bunch of automated stuff that runs when you make a PR. Everything has to pass though. More info here:
https://learn.adafruit.com/the-well-automated-arduino-library
The current PR is failing on clang formatting:
https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

This CI stuff can be not-fun when you first have to deal with it. But this is also a good PR, since it's relatively simple, to practice on.

I'd also suggest making the `R1` and `R2` #defs more verbose. Something like `VBAT_DIVIDER_R1` and `VBAT_DIVIDER_R2`.

**Comment by axelmagnus** [comment]
Oh, youre right Carter, CI stuff is not-fun. ill put that in the long term todo-list. 

but alas, it was a good thing it failed, because i found more errors in the comment text itself. I made the names more verbose and natural and used the suggestion from clang from the error msg.

**Comment by caternuson** [comment]
Thanks. It's failing on clang formatting again. It's a very simple issue, just trailing white space on these two lines:
```
  * resistor between ADC and the BAT pin (RESISTOR_BAT) and a 10K Resistor 
  * between ADC and Ground (RESISTOR_GND) or change the values below for other 
```

**Comment by axelmagnus** [comment]
> 

thats just cruel for a noob.

**Comment by caternuson** [comment]
Yah, dealing with the essentially cosmetic gripes is annoying. But the CI also catches real issues, and then you appreciate it more.

Thanks for the PR. Looks good and it's passing now, so let's merge it!

**Comment by axelmagnus** [comment]
maybe the commit msg should be "Fixed voltage divider formula for ESP8266"..

**Pull request merged**
